## 넘파이 임포트 

In [1]:
import numpy as np

## 생성 함수 

In [2]:
li = [1,2,3,4,5]
print(type(li))

<class 'list'>


In [4]:
arr = np.array(li) #ndarray로 변환
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## np.arange() 

파이썬 range 함수와 같지만 ndarray 객체를 생성한다는 차이가 있다.

In [5]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

## np.zeros(), np.ones(), np.full() 

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.zeros((2,3))

In [13]:
print(arr.shape)

(2, 3)


In [14]:
arr = np.zeros((2,2,2))
print(arr)
print(arr.shape)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2, 2)


In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [15]:

arr = np.ones((2,2,2))
print(arr)
print(arr.shape)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
(2, 2, 2)


In [16]:
arr = np.full((2,2,2),7)
print(arr)
print(arr.shape)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
(2, 2, 2)


## 항등 행렬 

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 형상 관련 함수 

In [18]:
arr = np.arange(1,6)

In [19]:
arr.shape

(5,)

In [20]:
len(arr)

5

## np.reshape 

In [22]:
arr = np.arange(1,7)
arr


array([1, 2, 3, 4, 5, 6])

In [24]:
arr = np.reshape(arr,(2,3))

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
print(arr[1,1] == arr[1][1])

True


In [32]:
arr = np.reshape(arr,(3,2))

In [33]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

## -1은 해당 행 또는 열은 터치하지 않는다 

In [35]:
arr = np.reshape(arr,(-1,3))

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr = np.reshape(arr,(3,-1))

In [39]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

### 행 벡터를 열 벡터로 바꾼다 

In [47]:
arr = np.arange(1,6)
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [48]:
arr = np.reshape(arr,(5,1))

In [49]:
arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [50]:
arr = np.reshape(arr,(-1,1))

In [51]:
arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [52]:
print(arr.shape)

(5, 1)


### 행렬의 전치 

In [53]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
arr = np.reshape(arr,(2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 난수 발생 함수 

In [57]:
np.random.randint(1,10)

9

In [74]:
np.random.randint(1,10,5)

array([2, 3, 8, 1, 4])

(가우시안 정규분포)

평균은 0에 수렴, 표준편차는 1에 수렴 

In [204]:
arr = np.random.randn(1000)
np.mean(arr)

0.06287012807273029

In [233]:
np.std(arr)

1.0115356101827706

## 랜덤 seed 지정하기

In [236]:
np.random.seed(42)

### numpy 연산 함수 

In [238]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
c

array([5, 7, 9])

### numpy 배열의 Broadcast 연산

In [240]:
a = np.array([1,2,3])
b = 10
c = a+b
c

array([11, 12, 13])

In [241]:
a = np.array([[1,2],[3,4]])
b = 10
c = a+b
c

array([[11, 12],
       [13, 14]])

In [242]:
a = np.array([[1,2],[3,4]])
b = np.array([10,20])
c = a+b
c

array([[11, 22],
       [13, 24]])

### 넘파이 Array의 인덱싱 

In [4]:
import numpy as np
arr1 = np.arange(10)

In [9]:
arr1[3]

3

In [10]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [11]:
type(arr1[3:9])

numpy.ndarray

In [12]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2차원 배열의 인덱싱 

In [14]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [15]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr3 = np.arange(1,13)

In [17]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
arr3 = np.reshape(arr3,(-1,4))

In [19]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr2[0,0]

1

In [21]:
arr2[:,2]

array([ 3,  7, 11])

In [22]:
arr2[:,2].shape # 1차원

(3,)

In [23]:
arr2[2,:]

array([ 9, 10, 11, 12])

In [24]:
arr2[2,:].shape

(4,)

In [25]:
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [26]:
arr2[:,1:3].shape

(3, 2)

In [28]:
arr2[:,[1,3]] 
#행 전체, 1열과 3열 추출한 것을 하나의 행렬로, 추후에 헷갈릴 수 있을 것 같음 

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [33]:
arr2[[1,2],[0,2]]

array([ 5, 11])

### Array boolean 인덱싱(마스크) 

In [34]:
data = np.arange(16)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
data = np.reshape(data, (-1,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
data[:,2]

array([ 2,  6, 10, 14])

In [38]:
names = np.array(['Kim','Lee','Park','Choi'])
names

array(['Kim', 'Lee', 'Park', 'Choi'], dtype='<U4')

In [39]:
names_mask = names == 'Lee'

In [40]:
names_mask

array([False,  True, False, False])

In [45]:
data[:,names_mask]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [48]:
data[data[:,0]>4, :]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Numpy 함수 

In [49]:
data = np.arange(16).reshape((4,4))

In [50]:
np.sqrt(data) #루트입니드아! == **0.5

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [51]:
np.square(data) #제곱입니드아! == **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [54]:
np.exp(data) #e^x라고 할 수 있음

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [55]:
np.log(data) # 로그e를 취하는 것

C:\Users\edu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [56]:
np.log(np.exp(data))

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [57]:
np.exp(np.log(data))

C:\Users\edu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [58]:
np.sign(data) # 부호를 추출하는 함수 양수 = 1

array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [60]:
a = np.log(data)
a

C:\Users\edu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [61]:
np.isinf(a) # 무한대를 추출

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 통계함수 

In [62]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.sum(data)

120

In [66]:
np.sum(data,axis=1)
#axis -> 우선 data는 (4,4) 형태인데 0은 첫번쨰 인덱스, 1은 두번쨰 인덱스 이므로 각각 행과 열을 의미한다.
#즉 axis = 1은 열간 합을 의미한다.

array([ 6, 22, 38, 54])

In [67]:
np.sum(data,axis = 0)

array([24, 28, 32, 36])

In [68]:
np.mean(data)

7.5

In [69]:
np.mean(data,axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])

In [70]:
np.mean(data,axis = 0)

array([6., 7., 8., 9.])

In [71]:
np.max(data)

15

In [72]:
np.min(data)

0

In [73]:
np.argmax(data, axis = 0) # 가장 큰 값의 인덱스를 반환한다.

array([3, 3, 3, 3], dtype=int64)

In [74]:
np.argmax(data,axis = 1)

array([3, 3, 3, 3], dtype=int64)

In [75]:
np.argmin(data, axis = 0)

array([0, 0, 0, 0], dtype=int64)

### 행렬 곱 

In [77]:
a = np.array([1,2,3])
b = np.array([2,2,2])

In [78]:
np.dot(a,b)

12

In [79]:
np.sum(a*b)

12

In [81]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,2],[2,2]])
np.sum(a*b)

20

In [82]:
np.dot(a,b) # 행렬곱

array([[ 6,  6],
       [14, 14]])

In [83]:
a*b

array([[2, 4],
       [6, 8]])

In [96]:
x = np.array([[1,2],
              [3,4],
              [5,6]])
n_features = 2
units = 2
w1 = np.ones((n_features,units))
print(w1)
print('')
b1 = np.zeros(units)
print(b1)
print('')
z = np.dot(x,w1) + b1
#3x2 dot 2x2 + 1x2 //boradcast//
#입력 3개, 결과 2개 -> output 3x2로 도출
print(z.shape)
print('')
print(z)



[[1. 1.]
 [1. 1.]]

[0. 0.]

(3, 2)

[[ 3.  3.]
 [ 7.  7.]
 [11. 11.]]


### 고차원 배열 사용법 

In [108]:
x = np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]]])

In [109]:
x.shape

(2, 2, 2)

In [111]:
len(x)

2

In [112]:
x[0]

array([[1, 2],
       [3, 4]])

In [113]:
x[1]

array([[5, 6],
       [7, 8]])

In [114]:
x[0][0]

array([1, 2])

In [117]:
a = np.array([[1,2],[3,4]])
a.T

array([[1, 3],
       [2, 4]])

In [118]:
np.swapaxes(a,0,1)

array([[1, 3],
       [2, 4]])

In [119]:
x.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [120]:
np.swapaxes(x,0,2)

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [123]:
np.swapaxes(x,0,2)

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [125]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [126]:
x[1][0][0]

5

In [127]:
x[0][1][0]

3

In [128]:
x[0][2][0]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [129]:
np.swapaxes(x,0,1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [132]:
y= np.swapaxes(x,0,1)

In [133]:
y[0][1][0]

5

In [135]:
np.swapaxes(x,1,2)

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [137]:
np.sum(x,axis=2)

array([[ 3,  7],
       [11, 15]])

In [138]:
np.sum(x,axis=1)

array([[ 4,  6],
       [12, 14]])

In [139]:
np.sum(x,axis = 0)

array([[ 6,  8],
       [10, 12]])

In [148]:
x = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])

In [149]:
x

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [150]:
np.sum(x,axis=3)

array([[[ 3,  7],
        [11, 15]],

       [[19, 23],
        [27, 31]]])

In [152]:
np.sum(x,axis=2)

array([[[ 4,  6],
        [12, 14]],

       [[20, 22],
        [28, 30]]])

In [153]:
np.sum(x,axis=1)

array([[[ 6,  8],
        [10, 12]],

       [[22, 24],
        [26, 28]]])

In [154]:
np.swapaxes(x,0,3)

array([[[[ 1,  9],
         [ 3, 11]],

        [[ 5, 13],
         [ 7, 15]]],


       [[[ 2, 10],
         [ 4, 12]],

        [[ 6, 14],
         [ 8, 16]]]])

In [156]:
np.swapaxes(x,1,2)

array([[[[ 1,  2],
         [ 5,  6]],

        [[ 3,  4],
         [ 7,  8]]],


       [[[ 9, 10],
         [13, 14]],

        [[11, 12],
         [15, 16]]]])

In [158]:
np.swapaxes(x,0,1)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 9, 10],
         [11, 12]]],


       [[[ 5,  6],
         [ 7,  8]],

        [[13, 14],
         [15, 16]]]])

In [160]:
np.swapaxes(x,2,3)

array([[[[ 1,  3],
         [ 2,  4]],

        [[ 5,  7],
         [ 6,  8]]],


       [[[ 9, 11],
         [10, 12]],

        [[13, 15],
         [14, 16]]]])

In [161]:
x.shape

(2, 2, 2, 2)

In [173]:
x = np.array([[[[10],[12]],[[14],[15]]]])

In [174]:
x.shape

(1, 2, 2, 1)

In [177]:
np.swapaxes(x,0,2)

array([[[[10]],

        [[14]]],


       [[[12]],

        [[15]]]])

In [3]:
x = np.arange(36).reshape((2,2,3,3))

In [4]:
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [181]:
x.shape

(2, 2, 3, 3)

In [5]:
np.swapaxes(x,0,3)

array([[[[ 0, 18],
         [ 3, 21],
         [ 6, 24]],

        [[ 9, 27],
         [12, 30],
         [15, 33]]],


       [[[ 1, 19],
         [ 4, 22],
         [ 7, 25]],

        [[10, 28],
         [13, 31],
         [16, 34]]],


       [[[ 2, 20],
         [ 5, 23],
         [ 8, 26]],

        [[11, 29],
         [14, 32],
         [17, 35]]]])

In [8]:
import numpy as np
np.swapaxes(x,0,2)

array([[[[ 0,  1,  2],
         [18, 19, 20]],

        [[ 9, 10, 11],
         [27, 28, 29]]],


       [[[ 3,  4,  5],
         [21, 22, 23]],

        [[12, 13, 14],
         [30, 31, 32]]],


       [[[ 6,  7,  8],
         [24, 25, 26]],

        [[15, 16, 17],
         [33, 34, 35]]]])

In [ ]:
lllllllllllllslslslslllllllllllllllll