## 부동소수점 끼리 연산하기 

In [2]:
0.2 * 3 == 0.6

False

In [8]:
def a(x,y,plaes = 6):
    return round(abs(x-y), 6) == 0


a(3.14,3.14)

True

## 정수와 부동소수점 메서드 

In [9]:
divmod(34,3)

(11, 1)

In [11]:
a = round(113.23,-1)
b = round(123.23123123,4)
print(a,b)

110.0 123.2312


## fraction 모듈 

In [20]:
from fractions import Fraction


In [21]:
def rounding_floats(number1, places):
    return round(number1, places)

In [33]:
def float_to_fractions(number):
    return Fraction(*number.as_integer_ratio())

In [37]:
def get_denominator(number1,number2):
    """분모를 반환한다."""
    a = Fraction(number1, number2)
    return a.denominator

In [38]:
def get_numerator(number1, number2):
    a = Fraction(number1,number2)
    return a.numerator

In [39]:
def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1,number2) == 1.2)#assert -> true이면 넘어가고 false이면 exception 발생
    assert(rounding_floats(number1*10,number3) == 10)
    assert(float_to_fractions(number1) == number4)
    assert(get_denominator(number2,number6) == number6)
    assert(get_numerator(number2,number6) == number2)

In [40]:
test_testing_floats()

## decimal 모듈

In [45]:
sum(0.1 for i in range(10)) == 1.0

False

In [46]:
from decimal import Decimal
sum(Decimal('0.1') for i in range(10)) == Decimal('1.0')

True

## 2진수, 8진수, 16진수

In [51]:
print(bin(999))
print(oct(999))
print(hex(999))

0b1111100111
0o1747
0x3e7


In [60]:
def convert_to_decimal(number, base):
    multiplier, result = 1,0
    while number>0:
        result += number %10 * multiplier
        multiplier *= base
        number = number // 10
    return result

def test_convert_to_decimal():
    number, base = 1001, 4
    assert(convert_to_decimal(number, base) == 65)
    print('pass')

In [61]:
test_convert_to_decimal()


pass


In [72]:
def convert_from_larger_bases(number, base):
    strings = '0123456789ABCDEFGHIJ'
    result = ''
    while number>0:
        digit = number % base
        result = strings[digit] + result
        number = number // base
    return result

def test_convert_from_larger_bases():
    number, base = 31,16
    assert(convert_from_larger_bases(number, base) == '1F')
    print('pass')
    
# if __name__ == '__main__':
#     test_convert_from_larger_bases()

In [73]:
test_convert_from_larger_bases()

pass


In [76]:
def convert_dec_to_any_base_rec(number, base):
    convertString = '0123456789ABCDEF'
    if number < base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number//base,base) + convertString[number % base]
    
def test_convert_dec_to_any_rec():
    number = 9
    base = 2
    assert(convert_dec_to_any_base_rec(number, base) == '1001')
    print('pass')
    
# if __name__ == '__main__':
#     test_convert_from_larger_bases()

In [77]:
convert_dec_to_any_base_rec()

TypeError: convert_dec_to_any_base_rec() missing 2 required positional arguments: 'number' and 'base'

## 최대공약수 (호제법)

In [79]:
 def finding_gcd(a,b):
    while(b != 0):
        result = b
        a,b = a, a%b
    return result

def test_finding_gcd():
    n1 = 21
    n2 = 12
    assert(finding_gcd(n1,n2) == 3)
    print('pass')
    
if __name__ == "__main__":
    test_finding_gcd()

pass


## Random 모듈 

In [115]:
import random

def testing_random():
    values = [1,2,3,4]
    print("random 모듈 테스트")
    print(random.choice(values))
    print(random.choice(values))
    print(random.choice(values))
    print(random.sample(values,2))
    print(random.sample(values,3))
    
    print("shuffle from random module")
    random.shuffle(values)
    print(values)

    print("범위 내의 임의의 숫자")
    print(random.randint(0,10))
    print(random.randint(0,20))
    
if __name__ == "__main__":
    testing_random()
    

random 모듈 테스트
4
4
3
[3, 1]
[4, 3, 2]
shuffle from random module
[2, 3, 1, 4]
범위 내의 임의의 숫자
5
0


## 피보나치 수열 

In [123]:
import math

def find_fibonacci_seq_form(n):
    sq5 = math.sqrt(5)
    phi = (1 + sq5) /2
    return int(math.floor(phi ** n / sq5))
find_fibonacci_seq_form(11)

88

In [127]:
def fib_generator():
    a,b = 0,1
    while True:
        yield b #yield -> not a function, generator
        a,b = b, a+b
        #yield가 있으면 한바뀌 돌고 yield에서 멈추고, 호출 할 때마다 
        #새로 초기화 된 yield가 return된다.
        
if __name__ == "__main__":
    fg = fib_generator()
    for _ in range(10):
        print(next(fg), end = ' ')# next --> 순회

1 1 2 3 5 8 13 21 34 55 

## 소수 (Prime number)

In [154]:
import math
import random

def finding_prime(number):
    num = abs(number)
    if num < 4 : return True #2,3은 모두 소수
    for x in range(2,num):
        if num % x == 0:
            return False
    return True

def test_finding_prime():
    number = 17
    assert(finding_prime(number))
    print('pass')

In [155]:
if __name__ == "__main__":
    test_finding_prime()

pass


In [156]:
import math
import random

def finding_prime_sqrt(number):
    num = abs(number)
    if num < 4 : return True #2,3은 모두 소수
    for x in range(2,int(math.sqrt(num)+1)):
        if num % x == 0:
            return False
    return True

def test_finding_prime():
    number = 17
    assert(finding_prime(number) == True)
    assert(finding_prime_sqrt(number) == True)
    print('pass')

In [157]:
if __name__ == "__main__":
    test_finding_prime()

pass


In [158]:
import math
import random

def finding_prime_sqrt(number):
    num = abs(number)
    if num < 4 : return True #2,3은 모두 소수
    for x in range(2,int(math.sqrt(num)+1)): #소수가 아니라면 입력값의 약수의 최대는 입력값의 제곱근이기 때문
        if num % x == 0:
            return False
    return True

def test_finding_prime():
    number = 17
    assert(finding_prime(number) == True)
    assert(finding_prime_sqrt(number) == True)
    print('pass')

In [159]:
def finding_prime_fermat(number):
    if number < 102:
        for a in range(2, number):
            if pow(a, number -1 , number) != 1 :
                return False
        return True
    else:
        for i in range(100):
            a = random.randint(2, number -1)
            if pow(a,number-1,number) !=1:
                return False
        return True


In [160]:
finding_prime_fermat(18)

False

##  넘파이 패키지

In [164]:
import numpy as np

In [165]:
np.array(((1,2,3),(4,5,6),(7,8,9)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
x = np.array(((1,2,3),(4,5,6),(7,8,9)))
x.ndim

2

In [168]:
x.shape

(3, 3)

In [184]:
def testing_numpy():
    ax = np.array([1,2,3])
    ay = np.array([3,4,5])
    print(ax)
    print(ax*2)
    print(ax+10)
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax-ay)
    print(np.where(ax<2,ax,15))
    
    m = np.matrix([ax,ay,ax])
    print(m)
    print(m.T)
    
    grid1 = np.zeros(shape=(10,10), dtype=float)
    grid2 = np.ones(shape=(10,10), dtype=float)
    print(grid1)
    print(grid2)
    print(grid1[1] + 10)
    print(grid2[:,2]*2)
    
if __name__ == "__main__":
    testing_numpy()

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 15 15]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [271]:
import numpy as np
import time

def trad_version():
    t1 = time.time()
    x =  range(10000000)
    y =  range(10000000)
    z = []
    for i in range(len(x)):
        z.append(x[i] + y[i])
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    x = np.arange(10000000)
    y = np.arange(10000000)
    z = x + y
    return time.time() - t1

if __name__ == "__main__":
    print(trad_version())
    print(numpy_version())

0.04948139190673828


## 깊은 복사와 슬라이싱 연산 

## 가변성 

In [280]:
myList = [1,2,3,4]
newList = myList[:]
newList2 = list(myList)
myList2 = myList.copy()

In [281]:
print(id(myList), id(newList), id(newList2), id(myList2))

1682506912136 1682507298184 1682507122248 1682507155592


In [278]:
people= {"버피","에인절","자일스"}
slayers = people.copy()
slayers.discard("자일스")
slayers.remove("에인절")
slayers

{'버피'}

In [279]:
people

{'버피', '에인절', '자일스'}

In [282]:
myDict = {"안녕":"세상"}
newDict = myDict.copy()

In [283]:
newDict

{'안녕': '세상'}

In [284]:
print(id(myDict), id(newDict))

1682507398664 1682507088664


## 슬라이싱 연산자 

In [292]:
word = "뱀파이어를 조심해!"
word[-1]
word[-5:]
word[-0]

'뱀'

##  Tuple

In [294]:
t1 = 1234, 'hi!'

In [295]:
t1

(1234, 'hi!')

In [296]:
t2 = t1, (1,2,3,4,5)

In [297]:
t2

((1234, 'hi!'), (1, 2, 3, 4, 5))

In [298]:
empty = ()

In [301]:
t1 = 'hi',

In [302]:
t1

('hi',)

In [303]:
len(t1)

1

## 튜플 언패킹 

In [304]:
a,b = (1,2,3)

ValueError: too many values to unpack (expected 2)

In [305]:
a,b,c = (1,2,3)

In [306]:
print(a,b,c)

1 2 3


In [307]:
a,*b = (1,2,3)

In [308]:
print(a,b)

1 [2, 3]


In [309]:
*a,b = (1,2,3)

In [310]:
print(a,b)

[1, 2] 3


In [311]:
a,b,*c = (1,2,3,4,5,5,1,2,3,3)

In [312]:
print(a,b,c)

1 2 [3, 4, 5, 5, 1, 2, 3, 3]


## 네임드 튜플

In [313]:
import collections

Person = collections.namedtuple('Person','name age gender')
p = Person(name = 'Joo', age = 30, gender = 'male')
p

Person(name='Joo', age=30, gender='male')

In [314]:
p.name

'Joo'

In [315]:
p.age

30

In [316]:
p.gender

'male'

## 리스트 컨프리헨션 

In [326]:
a = [ _ for i in range(10)]

In [329]:
a = [i for i in range(1500,1560) if i%4 == 0]

In [330]:
a

[1500,
 1504,
 1508,
 1512,
 1516,
 1520,
 1524,
 1528,
 1532,
 1536,
 1540,
 1544,
 1548,
 1552,
 1556]

In [331]:
b = [2**i for i in range(13)]

In [332]:
b

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]

## 바이트와 바이트 배열 

In [333]:
blist = [1,2,3,255]
the_bytes = bytes(blist)
the_bytes

b'\x01\x02\x03\xff'

In [334]:
the_byte_array = bytearray(blist)
the_byte_array

bytearray(b'\x01\x02\x03\xff')

In [335]:
the_bytes[1] = 127

TypeError: 'bytes' object does not support item assignment

In [336]:
the_byte_array[1] = 127

In [347]:
the_byte_array

bytearray(b'\x01\x7f\x03\xff')

In [352]:
x = 0x12345678


def bit_count(a):
    count = 0
    for i in range(32):
        if a & (1<<i) != 0 :
            count += 1
    return count
bit_count(x)

0.0


13

In [354]:
x = 0x12345678

def bit_count_new(a):
    count = 0
    while a != 0 :
        a = a &(a-1)
        print(a)
        count +=1
    return count

bit_count_new(x)

305419888
305419872
305419840
305419776
305419264
305418240
305414144
305397760
305135616
304087040
301989888
268435456
0


13

In [374]:
def revert(string):
    str = string[::-1]
    return str

a= '주상현'
revert(a)

'현상주'

In [3]:
def reverser(string1, p1 = 0, p2 = None):
    if len(string1) <2 :
        return string1
    p2 = p2 or len(string1) -1
    while p1 < p2:
        string1[p1], string1[p2] = string1[p2], string1[p1]
        p1 += 1
        p2 -= 1

In [32]:
def reversing_words_setence_logic(string1):
    reverser(string1)
    p = 0
    start = 0
    while p < len(string1):
        if string1[p] == u"\u0020":
            reverser(string1,start,p-1)
            start = p+1
        p +=1
    print(start, p)
    reverser(string1, start, p-1)
    return "".join(string1)


In [35]:
reversing_words_setence_logic(list('well done'))

5 9


'done well'

In [36]:
def reverse_words_brute(string):
    word, sentence = [],[]
    for character in string:
        if character != " ":
            word.append(character)
        else:
            if word:
                sentence.append("".join(word))
            word = []
    if word != "":
        sentence.append("".join(word))
    sentence.reverse()
    return " ".join(sentence)

str1 = "python is really fun"
str2 = reverse_words_brute(str1)
print(str2)

fun really is python


In [39]:
a = [1,2,3]
a.reverse()

In [40]:
a

[3, 2, 1]

In [41]:
def reversing_words_slice(word):
    new_word = []
    words = word.split(" ")
    for word in words[::-1]:
        new_word.append(word)
    return " ".join(new_word)

str1 = 'python is really fun'
str2 = reversing_words_slice(str1)
print(str2)

fun really is python


## 단순 문자열 단축 

In [1]:
def str_compression(s):
    count, last = 1, ""
    list_aux = []
    for i,c in enumerate(s):
        if last == c:
            count +=1
        else:
            if i != 0:
                list_aux.append(str(count))
            list_aux.append(c)
            count = 1
            last = c
    list_aux.append(str(count))
    return "".join(list_aux)

if __name__ == "__main__":
    result = str_compression("aabcccccaaa")
    print(result)

a2b1c5a3


## 문자열 순열 

In [5]:
import itertools

def perm(s):
    if len(s) <2:
        return s
    res = []
    for i,c in enumerate(s):
        for cc in perm(s[:i] +s[i+1:]):
            res.append(c + cc)
    return res

def perm2(s):
    res = itertools.permutations(s)
    
    
if __name__ == "__main__":
    val = '123'
    print(perm(val))

['123', '132', '213', '231', '312', '321']


In [8]:
s = [0,1,2]
print(s[:1])
print(s[2:])

[0]
[2]


In [12]:
a = [0,1,2]
for i,c in enumerate(a):
    print(i,c)

0 0
1 1
2 2


In [14]:
def combinations(s):
    if len(s) <2:
        return s
    res = []
    for i,c in enumerate(s):
        res.append(c)
        for j in combinations(s[:i] + s[i+1:]):
            res.append(c+j)
    return res
    
if __name__ == "__main__":
    result = combinations("abc")
    print(result)

['a', 'ab', 'abc', 'ac', 'acb', 'b', 'ba', 'bac', 'bc', 'bca', 'c', 'ca', 'cab', 'cb', 'cba']


## 회문 

In [23]:
def is_palindrome(s):
    l = s.split(" ")
    s2 = "".join(l)
    return s2 == s2[::-1]

def is_palindrome2(s):
    l = len(s)
    f,b = 0,l-1
    
    while f < l//2:
        while s[f] == " ":
            f += 1
        while s[b] == " ":
            b -= 1
        if s[f] != s[b] :
            return false
        f += 1
        b -= 1
        return True

def is_palindrome3(s):
    s = s.strip() #공백 제거
    if len(s) < 2:
        return True
    if s[0] == s[-1] :
        return is_palindrome3(s[1:-1])
    
if __name__ == "__main__":
    str1 = "다시 합창합시다"
    print(is_palindrome(str1))
    print(is_palindrome2(str1))
    print(is_palindrome3(str1))

True
True
True


In [25]:
dir(set)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']